import {
  getNursingVitalStatus,
  VitalKind,
  VitalStatus,
} from '../src/utils/nursingVitalStatus';

test.each<[VitalKind, string, VitalStatus]>([
  ['hr', '60', 'normal'],
  ['hr', '100', 'normal'],
  ['hr', '101', 'moderate'],
  ['hr', '120', 'moderate'],
  ['hr', '121', 'high'],
  ['hr', '151', 'high'],
  ['bp', '119/79', 'normal'],
  ['bp', '120/79', 'moderate'],
  ['bp', '129/79', 'moderate'],
  ['bp', '130/79', 'high'],
  ['bp', '118/80', 'high'],
  ['bp', '154/96', 'high'],
  ['bp', '180/79', 'high'],
  ['bp', '119/120', 'high'],
  ['spo2', '100%', 'normal'],
  ['spo2', '95%', 'normal'],
  ['spo2', '94%', 'moderate'],
  ['spo2', '93%', 'moderate'],
  ['spo2', '92%', 'high'],
  ['spo2', '89%', 'high'],
  ['rr', '12', 'normal'],
  ['rr', '20', 'normal'],
  ['rr', '21', 'moderate'],
  ['rr', '24', 'moderate'],
  ['rr', '25', 'high'],
  ['rr', '31', 'high'],
  ['temperature', '36.1°C', 'normal'],
  ['temperature', '37.5°C', 'normal'],
  ['temperature', '37.6°C', 'moderate'],
  ['temperature', '37.9°C', 'moderate'],
  ['temperature', '38°C', 'high'],
  ['temperature', '40°C', 'high'],
  ['temperature', '98.6°F', 'normal'],
  ['temperature', '100.1°F', 'moderate'],
  ['temperature', '100.4°F', 'high'],
  ['hr', '59', 'unknown'],
  ['rr', '11', 'unknown'],
  ['temperature', '35°C', 'unknown'],
  ['temperature', '98.6', 'unknown'],
  ['bp', '120/', 'unknown'],
  ['spo2', '101%', 'unknown'],
  ['hr', '', 'unknown'],
  ['hr', '88invalid', 'unknown'],
])('%s reading %s is %s', (kind, reading, expected) => {
  expect(getNursingVitalStatus(kind, reading)).toBe(expected);
});
